sudo: false

language: node_js

node_js:
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"

install:
  - npm install
  - npm run build

script:
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules
